#!/bin/sh
. ../SourceMe64
echo "1" > /tmp/result
HERE=`pwd`
rm -f ../../Deploy/m7-idbloader.img ../../Deploy/m7-uboot.img ../../Deploy/m7-trust.img
BOOT_M7_FROM_DEPLOY="../Bootloader/u-boot-novasomM7-2017.09"
BOOT_M7="../${BOOT_M7_FROM_DEPLOY}"
echo "1" > /tmp/result
cd ${BOOT_M7}
make distclean
[ "$?" != "0" ] && exit
mv .git gitb.git
make mrproper
[ "$?" != "0" ] && exit
./make.sh evb-rk3328
[ "$?" != "0" ] && exit
cp ${HERE}/rkbin/rk322xh_miniloader_v2.46.bin .
cp ${HERE}/rkbin/rk3328_ddr_333MHz_v1.13.bin .
cp ${HERE}/rkbin/rk3328_ddr_786MHz_v1.13.bin .
./do_idbloader.sh
[ "$?" != "0" ] && exit
mv gitb.git .git
HERE=`pwd` 
cd ../../Deploy
ln -s ${BOOT_M7_FROM_DEPLOY}/idbloader.img m7-idbloader.img
ln -s ${BOOT_M7_FROM_DEPLOY}/uboot.img m7-uboot.img
ln -s ${BOOT_M7_FROM_DEPLOY}/trust.img m7-trust.img
echo "0" > /tmp/result
