#!/bin/sh
DISK=$1
FS=$2
DTB_SDL=$3
DTB_Q=$4
. ./version
echo "Writing $2 on $1"
! [ -z $3 ] && echo "Using $3 as custom dtb"
! [ -z $4 ] && echo "Using $4 as additional custom dtb"
bzcat ${FS} | sudo dd of=${DISK} bs=4M status=progress
sync

if ! [ -z "${3}" ]; then
	rm -rf ext_tmp
	mkdir ext_tmp
	sudo mount ${DISK}1 ext_tmp
	sudo cp /Devel/NOVAsdk${VERSION}/DtbUserWorkArea/${3} ext_tmp/.
	if ! [ -z "${4}" ]; then
		sudo cp /Devel/NOVAsdk${VERSION}/DtbUserWorkArea/${4} ext_tmp/.
	fi
	sync
	sudo umount ext_tmp
fi

echo 0 > /tmp/result
return 0
