#!/bin/sh
. ./version
UPD_ELEMENTS="\
Bootloader/u-boot-novasomM8-2017.11_${VERSION} \
Bootloader/u-boot-novasomP-2015.04_${VERSION} \
Bootloader/u-boot-novasomU-2016.03_${VERSION} \
Bootloader/u-boot-novasomM7-2017.09_${VERSION}"

cd /Devel/NOVAsdk${VERSION}
for i in ${UPD_ELEMENTS}; do
	HERE=`pwd`
	if [ -d ${i} ]; then
		cd ${i}
		echo -n "Working on ${i} ... "
		# u-boot was stopped during build, so .git has been shadowed from git. re push in place.
                if [ -d gitb.git ]; then
                        mv gitb.git .git
                fi
		git pull
		make distclean
	fi
	cd ${HERE}
done

