#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

mount /dev/mmcblk0p3 /mnt
if [ -d /mnt/sysconfig/ssh ]; then
	cp -r /mnt/sysconfig/ss* /etc/.
else
	# Create any missing keys
	/usr/bin/ssh-keygen -A
	if [ ! -d /mnt/sysconfig ]; then
		mkdir /mnt/sysconfig
	fi
	cp -r /etc/ss* /mnt/sysconfig/.
fi
umount /mnt
cat /etc/passwd | grep sshd  >/dev/null 2>&1
[ "$?" = "1" ] &&  echo "sshd:x:74:74:Privilege-separated SSH:/var/empty/sshd:/sbin/nologin" >> /etc/passwd
# sets a temporary password for root
echo -e "password\npassword" | passwd

umask 077

start() {
	echo -n "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}
stop() {
	echo -n "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

