#!/bin/sh
#
# apache2
#

start() {
	if [ -f /usr/bin/apachectl ]; then
		printf "Starting apache ... "
		mkdir -p /tmp/www/html
		echo "<html>" > /tmp/www/html/index.php
		echo " <head>" >> /tmp/www/html/index.php
		echo "  <title>NOVAsomM7 PHP Test</title>" >> /tmp/www/html/index.php
		echo " </head>" >> /tmp/www/html/index.php
		echo " <body>" >> /tmp/www/html/index.php
		echo " <?php phpinfo(); ?>" >> /tmp/www/html/index.php
		echo " </body>" >> /tmp/www/html/index.php
		echo "</html>" >> /tmp/www/html/index.php

		/usr/bin/apachectl -k start
		[ $? = 0 ] && echo "OK" || echo "FAIL"
	fi
}

stop() {
	if [ -f /usr/bin/apachectl ]; then
		printf "Stopping apache ... "
		/usr/bin/apachectl -k stop
		[ $? = 0 ] && echo "OK" || echo "FAIL"
	fi
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	;;
esac

