#!/bin/sh
# $1 = kernel
# $2 = source me file
. ../version
KERNEL=$1
SOURCEMEFILE=$2
echo "Working on ${KERNEL} with ${SOURCEMEFILE}"
echo "1" > /tmp/result
. ../${SOURCEMEFILE}
cd ../../Kernel/${KERNEL}
make -j32 Image
[ ! "$?" = "0" ] && exit
make -j32 modules
[ ! "$?" = "0" ] && exit
make qcom/apq8016-sbc.dtb
cd ../../Deploy
rm Image
ln -s ../Kernel/${KERNEL}/arch/arm64/boot/Image
echo "0" > /tmp/result
